### ISSUE TITLE
Unsloth Backend: Configure Finetuning / Inference YAMLs

### ISSUE THREAD

**Issue by sunraymoonbeam** [shafiqninaba/resonare#26]

**Comment by sunraymoonbeam** [comment]
Changing the model for fine-tuning requires manual updates in ```inference.yaml```, which is incorrect behavior.

Currently, both ```fine_tuning.yaml``` and ```inference.yaml``` contain duplicate model configuration parameters (e.g., model.name, chat_template, etc.). 

fine_tuning.yaml
```
model:
  name: unsloth/Llama-3.2-3B-Instruct-bnb-4bit #unsloth/gemma-3-4b-it
  max_seq_length: 2048
  dtype:
  load_in_4bit: true
  chat_template: llama-3.1 #gemma-3 
```

inference.yaml
```
model:
  name: unsloth/Llama-3.2-3B-Instruct-bnb-4bit #unsloth/gemma-3-4b-it 
  max_seq_length: 2048
  dtype:
  load_in_4bit: true
  chat_template: llama-3.1 #gemma-3

training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60
  learning_rate: 2e-4
  weight_decay: 0.01
  lr_scheduler_type: linear
  seed: 3407
  packing: false

output:
  dir: outputs
  report_to: none
```


Ideally, both processes should derive model metadata from a single source of truth. 

However, this becomes difficult when different models are involved, especially when ```run_id``` is used to fetch a trained model for inference. In such cases, we should consider pushing the model metadata to S3 during fine-tuning and loading the correct parameters during inference based on ```run_id```, to ensure consistency and decouple configuration.
